apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-manager-eventprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-manager-eventprocessor
  template:
    metadata:
      labels:
        app: money-manager-eventprocessor
    spec:
      containers:
        - name: money-manager-eventprocessor
          image: docker.io/library/money-manager-eventprocessor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"
